=== HamzaBoukaftane/MEAN-OnlyQuiz/server/assets/quiz-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "A quiz",
    "type": "object",
    "properties": {
        "id": {
            "description": "The unique identifier of the quiz",
            "type": "string"
        },
        "title": {
            "description": "The title of the quiz",
            "type": "string"
        },
        "duration": {
            "description": "Maximum time for a QCM question in seconds",
            "type": "number"
        },
        "lastModification": {
            "description": "The last modification date-time of the quiz in ISO8601 format",
            "type": [
                "string",
                "null"
            ],
            "format": "date-time"
        },
        "questions": {
            "description": "All questions part of the quiz",
            "type": "array",
            "items": {
                "description": "A quiz question",
                "type": "object",
                "properties": {
                    "type": {
                        "description": "The type of quiz. Multiple Choice (QCM) or Open Response (QRL)",
                        "type": "string",
                        "enum": [
                            "QCM",
                            "QRL"
                        ]
                    },
                    "text": {
                        "description": "The question itself",
                        "type": "string"
                    },
                    "points": {
                        "description": "The number of points assigned to the question. Has to be a multiple of 10.",
                        "type": "number"
                    },
                    "choices": {
                        "description": "The list of choices",
                        "type": [
                            "array"
                        ],
                        "minItems": 2,
                        "items": {
                            "description": "A choice",
                            "type": "object",
                            "properties": {
                                "text": {
                                    "description": "The choice itself",
                                    "type": "string"
                                },
                                "isCorrect": {
                                    "description": "A boolean which is true only when the choice is a correct answer",
                                    "type": [
                                        "boolean",
                                        "null"
                                    ]
                                }
                            },
                            "required": [
                                "text"
                            ]
                        }
                    }
                },
                "if": {
                    "properties": {
                        "type": {
                            "const": "QRL"
                        }
                    }
                },
                "then": {
                    "required": [
                        "type",
                        "text",
                        "points"
                    ],
                    "properties": {
                        "choices": {
                            "type": "null"
                        }
                    }
                },
                "else": {
                    "required": [
                        "type",
                        "text",
                        "points",
                        "choices"
                    ]
                }
            }
        }
    },
    "required": [
        "id",
        "title",
        "duration",
        "questions"
    ]
}

=== HamzaBoukaftane/MEAN-OnlyQuiz/server/assets/quiz-example.json
{
    "$schema": "quiz-schema.json",
    "id": "1a2b3c",
    "title": "Questionnaire sur le JS",
    "duration": 60,
    "lastModification": "2018-11-13T20:20:39+00:00",
    "questions": [
        {
            "type": "QCM",
            "text": "Parmi les mots suivants, lesquels sont des mots clés réservés en JS?",
            "points": 40,
            "choices": [
                {
                    "text": "var",
                    "isCorrect": true
                },
                {
                    "text": "self",
                    "isCorrect": false
                },
                {
                    "text": "this",
                    "isCorrect": true
                },
                {
                    "text": "int"
                }
            ]
        },
        {
            "type": "QRL",
            "text": "Donnez la différence entre 'let' et 'var' pour la déclaration d'une variable en JS ?",
            "points": 60
        },
        {
            "type": "QCM",
            "text": "Est-ce qu'on le code suivant lance une erreur : const a = 1/NaN; ? ",
            "points": 20,
            "choices": [
                {
                    "text": "Non",
                    "isCorrect": true
                },
                {
                    "text": "Oui",
                    "isCorrect": null
                }
            ]
        }
    ]
}
